# Generated by Django 5.1.15 on 2026-10-01 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_paid_at_order_payment_method_and_more'),
        ('store', '0002_product_allows_customization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItemCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='customizations/logos/')),
                ('preview', models.ImageField(blank=True, upload_to='customizations/previews/')),
                ('design_data', models.JSONField(help_text='Normalized placement: view, x_pct, y_pct, width_pct, height_pct, rotation')),
                ('design_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='customization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='orders.lineitemcustomization'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='orders.lineitemcustomization'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('customization__isnull', True)), fields=('cart', 'variant'), name='unique_cart_variant_without_customization'),
        ),
    ]
