# Generated by Django 5.1.15 on 2026-10-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_lineitemcustomization_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitemcustomization',
            name='method',
            field=models.CharField(blank=True, choices=[('embroidery_chest', 'Ricamo — lato cuore/petto'), ('embroidery_large', 'Ricamo grande'), ('dtf_chest', 'DTF — lato cuore/petto'), ('dtf_large', 'DTF grande (formato A4)')], default='embroidery_chest', max_length=32),
        ),
    ]
