# Generated by Django 5.1.15 on 2026-10-01 17:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allows_customization',
            field=models.BooleanField(default=False, help_text='Customers can upload a logo and position it on this product.'),
        ),
        migrations.AddField(
            model_name='product',
            name='customization_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Extra charge per customized item (EUR).', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='mockup_front',
            field=models.ImageField(blank=True, help_text='Front mockup image for the logo customizer (falls back to primary product photo).', null=True, upload_to='mockups/'),
        ),
    ]
