# Generated by Django 5.1.15 on 2026-10-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_allows_customization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Manufacturer / brand name', max_length=100),
        ),
    ]
