# Generated by Django 5.1.15 on 2026-10-08 10:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productimage_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dtf_chest_enabled',
            field=models.BooleanField(default=False, help_text='DTF customization — heart/chest side.'),
        ),
        migrations.AddField(
            model_name='product',
            name='dtf_chest_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='dtf_large_enabled',
            field=models.BooleanField(default=False, help_text='Large DTF customization (A4 size).'),
        ),
        migrations.AddField(
            model_name='product',
            name='dtf_large_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='embroidery_chest_enabled',
            field=models.BooleanField(default=False, help_text='Embroidery customization — heart/chest side.'),
        ),
        migrations.AddField(
            model_name='product',
            name='embroidery_chest_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='embroidery_large_enabled',
            field=models.BooleanField(default=False, help_text='Large embroidery customization.'),
        ),
        migrations.AddField(
            model_name='product',
            name='embroidery_large_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='customization_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Legacy/minimum customization fee (EUR). Prefer per-method fees.', max_digits=10),
        ),
    ]
